### ISSUE TITLE
按照文档安装之后，无法新建模型，有一个js有错误导致的

### ISSUE THREAD

**Issue by antaeus365** [echoyl/deadmin#1]
/antadmin/umi.04674098.js
这个JS有错，使用演示站的https://echoyl.com/antadmin/umi.67afbff4.js这个文件替换就好了。
下个版本记得修复一下

**Comment by echoyl** [comment]
惊现第一个issue，感谢
演示站是最新的，包里面的更新没有那么及时。今天会发一个版本

**Comment by echoyl** [comment]
已发布0.9.7
我这边用阿里云的composer 拉取的一直都是0.9.2的。。。
手动将[拓展库](https://github.com/echoyl/sa) 拉取下覆盖后用下面的命令更新下 build后的dist文件
php artisan deadmin:publish --update
