### ISSUE TITLE
比如某个from里面有个radio，里面要加俩选项按钮咋加？比如选择性别的radio

### ISSUE THREAD

**Issue by antaeus365** [echoyl/deadmin#2]
比如某个from里面有个radio，里面要加俩选项按钮咋加？比如选择性别的radio。
另外，系统总体用着顺手，但是不知道自己缺了哪方便的技术栈，导致很多地方都有一些输入json的配置，完全不知道这些是做什么用的。

**Comment by echoyl** [comment]
1.编辑模型，在（假设字段是gender）这个字段设置中有一个数据json的配置，设置性别数组。将字段的form类型设置为radioButton。
2.打开form重新提交下当前表单项生效
明天我再优化下这个类型设置并添加到使用文档中

**Comment by antaeus365** [comment]
![image](https://github.com/user-attachments/assets/a7aeed1e-f759-4474-bf9f-037cd1e3746c)
![image](https://github.com/user-attachments/assets/7c7b2604-5d8e-4835-9d97-e76b5cdf7a48)
是这样配置么
这么配置完之后，去列表页新建或修改内容，会报错如下
![image](https://github.com/user-attachments/assets/774d439a-a9ce-4ba1-ac14-7440ba754846)

**Comment by echoyl** [comment]
[{"id":"male","title":"male"}, {"id":"female","title":"female"}]

**Comment by echoyl** [comment]
已更新 拉下拓展包
新增文档说明
[枚举类型使用](https://echoyl.com/#/enum)

**Comment by antaeus365** [comment]
![image](https://github.com/user-attachments/assets/1fe7e2ac-f810-4c05-9bb9-845bb1d7a23d)
没找到在哪里选择自定义类型tag呢

**Comment by echoyl** [comment]
字段类型里面有一个自定义选项，选择这个后在更多页面里面最下面有一个dom设置添加一项类型选择tag然后保存就可以了。不知道的话可以看我线上示例查看下这列的设置。爪机回复不能截图抱歉
