### ISSUE TITLE
开启可搜索后，貌似选择女还是能搜出性别男

### ISSUE THREAD

**Issue by antaeus365** [echoyl/deadmin#3]
![image](https://github.com/user-attachments/assets/91371288-8064-4154-ad8e-96389a3b6cfa)
![image](https://github.com/user-attachments/assets/74a14435-6c9a-43ce-bc9f-0f695c70991d)
开启可搜索后，貌似选择女还是能搜出性别男

**Comment by echoyl** [comment]
开启搜索的话，需要编辑模型，里面有个搜索设置，添加一项，字段输入gender然后类型选择=，再选择gender字段，保存后就可以搜索了，搜索的话建议选择下select类型，raidobutton在搜索栏不太好看。添加搜索设置后是会重新生成php文件的。
