### ISSUE TITLE
拷贝配置栏设置时，提示：拷贝成功，请到 src/defaultSettings.js 中替换默认配置，但是整个站点都搜不到defaultSettings.js这个文件，要如何替换？

### ISSUE THREAD

**Issue by antaeus365** [echoyl/deadmin#4]
![image](https://github.com/user-attachments/assets/a5d2e0c7-b64f-4908-be68-06e5ee58ff88)

**Comment by echoyl** [comment]
在系统配置页面中 主题设置中的 antdpro配置中粘贴
这个提示是antdpro的 defaultSettings.js暂时不会用上
![setting](https://github.com/user-attachments/assets/a9f440ef-4128-4d38-af34-de5381a149e4)
